apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: quarry

resources:
  - ../../../base/migration

images:
  - name: quarry-migration
    newName: quarry-migration
    newTag: kind
