apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: quarry

resources:
  - ../../../base/applications

images:
  - name: quarry-api
    newName: quarry-api
    newTag: kind
  - name: quarry-dispatcher
    newName: quarry-dispatcher
    newTag: kind
  - name: quarry-worker
    newName: quarry-worker
    newTag: kind
